# Generated by Django 3.0.6 on 2020-06-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='mentor',
            field=models.CharField(choices=[('mentor-one', 'mentor-one'), ('mentor-two', 'mentor-two')], default='', max_length=20),
        ),
    ]
