# Generated by Django 3.0.6 on 2020-06-12 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mentors',
            new_name='Mentor',
        ),
    ]
