# Generated by Django 3.0.6 on 2020-06-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('linkedInUrl', models.CharField(max_length=50)),
                ('occupation', models.CharField(choices=[('S', 'Student'), ('F', 'Faculty'), ('O', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=600)),
                ('mentor', models.CharField(choices=[('mentor-one', 'mentor-one'), ('mentor-two', 'mentor-two')], default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
